### ISSUE TITLE
Add some cookie-less web analytics

### ISSUE THREAD

**Issue by flynnduism** [spinkube/documentation#103]
Good to gather some insights on traffic patterns - ideally with Plausible, a GA alternative that does not set any cookies.

To implement this we would add a component to the site's Hugo config.toml as shown in their [install docs](https://plausible.io/docs/hugo-integration)  

```
theme = ["plausible-hugo"]  # Add this theme to your already existing other themes
[params.plausible]
  enable = true  # Whether to enable plausible tracking
  domain = "spinkube.dev"  # Plausible "domain" name/id in your dashboard
```

![Screen Shot 2024-03-12 at 10 10 17 AM](https://github.com/spinkube/documentation/assets/686194/57c50b52-c629-4900-8b74-28aa0b9fbf8d)

I've setup the account admin side of things - code update required to complete this.

**Comment by macolso** [comment]
I'll take a look into this today with some help from @karthik2804

**Comment by vdice** [comment]
Closed by https://github.com/spinkube/documentation/pull/106 right @macolso ?

**Comment by macolso** [comment]
Yes, feel free to close @vdice
