### ISSUE TITLE
Why isnt spin kube deploy not working by default?

### ISSUE THREAD

**Issue by codeitlikemiley** [spinkube/documentation#173]
I run this command

```sh
spin kube deploy --from ghcr.io/$GH_USER/$PROJECT::latest
# outputs  
spinapp.spin.fermyon.com/artas configured
```

but when i curl `curl localhost:3000`

that dont work?

Is this only applicable on `docker-dekstop` ? and not with `k3d-wasms-cluster` context? 

this is what i saw on the documentation:

https://www.spinkube.dev/docs/spin-operator/tutorials/integrating-with-docker-desktop/#deploying-our-spin-app-to-docker

<img width="470" alt="Screenshot 2024-05-29 at 5 19 54 PM" src="https://github.com/spinkube/documentation/assets/28816690/e106caea-d308-4539-ac1f-844efe414fe9">

are we limited only on using the set up with docker desktop ?

also how do we really make use of this ?

assuming we dont want to use fermyon cloud and deploy it to other service provider e.g. GKE?

Do you have any guide on about that , i believe that is not found on any documentation pertaining to spin kube

which utilize kubernetes...

Hope someone can answer this thanks

**Comment by vdice** [comment]
Hello @codeitlikemiley, I want to first check on the reference you are attempting to deploy: `ghcr.io/$GH_USER/$PROJECT::latest`.

Is this a Spin app that has been published via eg `spin registry push ghcr.io/$GH_USER/$PROJECT::latest`?  Or is it a Spin app wrapped in a Dockerfile and pushed via `docker push`?  Those are the two supported paths, with the former being the preferred/suggested and the latter a carryover from earlier versions of the [containerd-shim-spin](https://github.com/spinkube/containerd-shim-spin).

If it is neither of those but rather a 'regular' Docker image, this won't run as a SpinApp on Kubernetes via the Spin Operator.  (Though of course it can run as a standard Kubernetes Deployment/Pod!)

**Comment by bacongobbler** [comment]
I also noticed the tag includes two colons instead of one. It should be `ghcr.io/$GH_USER/$PROJECT:latest`, not `ghcr.io/$GH_USER/$PROJECT::latest`.

**Comment by bacongobbler** [comment]
Hi @codeitlikemiley. Any updates on your end?
