### ISSUE TITLE
Proposal: overhauling the site navigation

### ISSUE THREAD

**Issue by bacongobbler** [spinkube/documentation#189]
To me, the site's current navigation seems a little confusing. On one hand, it presents SpinKube as a holistic product for Kubernetes. On the other hand, it presents those topics under a specific sub-project, with most of the content heavily skewed towards the spin-operator project.

As seen here:

![spinkube.dev/docs Table of Contents](https://github.com/spinkube/documentation/assets/1360539/d5afdd0a-d550-4ec2-bace-fec191c70658)

I would like to propose the following changes to the site:

## Move away from spin-operator, more towards Spinkube

A large amount of the content in the spin-operator section describes high level Spinkube topics. Things like:

- Quickstart Guide
- Installation
- Tutorials
- Support/Feedback

The topics contained within these sub-sections are not specific to spin-operator.

## Move "Concept guides" into a new section called the "Reference guides"

All of these "Concepts" guides are incredibly short, forming only a few sentences at most. For example,

https://www.spinkube.dev/docs/containerd-shim-spin/concepts/
https://www.spinkube.dev/docs/runtime-class-manager/concepts/
https://www.spinkube.dev/docs/spin-plugin-kube/concepts/
https://www.spinkube.dev/docs/spin-trigger-mqtt/

I think it'd be better suited if these were places in a separate section known as the "Reference guides" where we could lay out high-level concepts about Spinkube's architecture, map those concepts back to these projects, and explain those projects in more detail.

## How this would look

In my head, the end result would be a table of contents that looks like this:

- Overview: A high level overview of SpinKube
- Quickstart: Learn how to setup a Kubernetes cluster, install Spinkube and run your first Spin App
- Topic Guides: discuss key topics and concepts at a fairly high level and provide useful background information and explanation
- Reference Guides: contains technical reference for APIs and other aspects of Spinkube's machinery. They describe how it works and how to use it but assume that you have a basic understanding of key concepts.
- Contributing: Learn about the development process for the Spinkube project and about how you can contribute
- Glossary: Glossary of terms

Thoughts?

**Comment by vdice** [comment]
👍 I really like the proposed direction @bacongobbler.  "Move away from spin-operator, more towards Spinkube" is a great (and timely) guiding principle here.  The current layout still represents a time when Spin Operator was _the_ main SpinKube resource but obviously it no longer is.  The rough sketch of ToC seems great to me!
