### ISSUE TITLE
Tutorial - OpenTelemetry support

### ISSUE THREAD

**Issue by bacongobbler** [spinkube/documentation#207]
From a question in the #spin channel in Fermyon's Discord server:

> Hi all, want to ask if there are any current blockers on taking this into a production environment. Have read through docs and code and hard to pin down exactly what spinkube can do right now. We are mainly concerned with redis and opentelemetry support

content related to redis support is being tracked in #40. We should write some content around opentelemetry support once that lands.

See also https://github.com/spinkube/spin-operator/issues/253

**Comment by calebschoepp** [comment]
@asteurer is working on this

**Comment by asteurer** [comment]
@bacongobbler Caleb and I chatted about where to house the docs for OTel in SpinKube, and we wanted double check you are okay with us adding an `Observing SpinKube` section in under `Using SpinKube`.

**Comment by bacongobbler** [comment]
absolutely!

**Comment by asteurer** [comment]
See https://github.com/spinkube/documentation/pull/226
