### ISSUE TITLE
Further 'copy to clipboard' issues

### ISSUE THREAD

**Issue by vdice** [spinkube/documentation#216]
In testing https://github.com/spinkube/documentation/pull/215 I noticed some more 'copy to clipboard' issues:

- instances where the 'copy to clipboard' icon is visible _but_ it doesn't appear to actually copy to my clipboard
  - for example: any 'copy-able' snippet from the [Quickstart doc](https://www.spinkube.dev/docs/install/quickstart/)
  - (My setup: Browser: Brave, Macbook Air M3)
- more instances where the 'copy to clipboard' icon is not visible
  - for example: the [Installing on Azure Kubernetes Service](https://www.spinkube.dev/docs/install/azure-kubernetes-service/) doc

**Comment by bacongobbler** [comment]
Error from console logs:

```
ReferenceError: Cannot access 'copyCode' before initialization
    at copyButton.onclick (click-to-copy.js:32:9)
copyButton.onclick @ click-to-copy.js:32
```

> more instances where the 'copy to clipboard' icon is not visible
> * for example: the [Installing on Azure Kubernetes Service](https://www.spinkube.dev/docs/install/azure-kubernetes-service/) doc

This makes sense - the copy-to-clipboard icon is present only when the following data appears to be present in the metadata:

```
```console { data-plausible="copy-quick-deploy-operator" }
```

I'm looking into how this works from docsy's side of things

**Comment by bacongobbler** [comment]
The issue with the button not appearing appears to stem from the following error log:

```
Uncaught DOMException: Failed to execute 'add' on 'DOMTokenList': The token provided must not be empty.
    at http://localhost:1313/js/click-to-copy.js:24:26
```

**Comment by bacongobbler** [comment]
Found the issue. Addressed in https://github.com/spinkube/documentation/pull/217/commits/8c2d3970174706623272c550a3e3a15a14bf6940.
