### ISSUE TITLE
CRD reference generation is broken

### ISSUE THREAD

**Issue by calebschoepp** [spinkube/documentation#236]
Problem: We run `crd-reference/generate.sh` in CI but it doesn't actually do anything because it isn't placing the generate files in the right location. This means that if we don't update the references they fall out of date.

Potential solution: Fix the script to actually place the files in the correct location. This has the downside that it will overwrite the aliases field in the front matter and I don't see a way with Crdoc to insert that. We'd have to write some sed or awk to do that for us.

**Comment by calebschoepp** [comment]
@bacongobbler how important is it that we keep the aliases on the CRD reference docs? If we could do away with that requirement than fixing this would be fairly straightforward.

**Comment by bacongobbler** [comment]
I'm not too concerned as long as nobody is currently referencing those aliases in other locations. Those aliases were put in place after https://github.com/spinkube/spin-operator/issues/279 was raised

**Comment by bacongobbler** [comment]
…Which was fixed in https://github.com/spinkube/spin-operator/pull/286. So it should be fine to remove those aliases.

**Comment by calebschoepp** [comment]
Sweet, more broadly does that mean we don't need those aliases anywhere in the codebase? Because maybe that could be another issue to remove the aliases which would simplify the codebase.
