### ISSUE TITLE
Document support policy for SpinKube

### ISSUE THREAD

**Issue by macolso** [spinkube/documentation#250]
It would be helpful to include either a footer or excerpt on the [Troubleshooting guide ](https://www.spinkube.dev/docs/contrib/troubleshooting/) about SpinKube's support policy. This will help set expectation with users, and can be repurposed as the support reference on SpinKube marketplace offerings as well. I'm imagining the message would be something along the lines of "SpinKube provides support on best effort basis - please file an issue under the appropriate repository and if urgent, amplify in Slack"

**Comment by calebschoepp** [comment]
I like your suggested message and I think the troubleshooting guide would be an appropriate place. It'd be great if you could open a PR for that.
