### ISSUE TITLE
Blog: What's up in the latest SpinKube releases?

### ISSUE THREAD

**Issue by macolso** [spinkube/documentation#254]
It would be helpful to create a blog post that dives into the latest work the SpinKube contributors have released this month to inspire others to get their hands on the latest version. I imagine this would heavily focus on the Spin Operator v0.4 and container-d-spin-shim v0.17 releases which are coming soon

**Comment by calebschoepp** [comment]
https://www.spinkube.dev/blog/2024/11/12/five-new-things-in-spinkube/
