### ISSUE TITLE
docs: in installation steps remove need to clone `spin-operator` repo

### ISSUE THREAD

**Issue by kate-goldenring** [spinkube/documentation#77]
Ideally, to install spinkube, i should not have to clone the repo. Do we need this `make install`  in the [installation steps](https://www.spinkube.dev/docs/spin-operator/installation/installing-with-helm/#prepare-the-cluster) to install the CRDs or is it bundled in the Helm chart, @vdice?

**Comment by macolso** [comment]
@kate-goldenring what's the status of this issue? See the PR is closed but issue is open. 

I was going to open a PR to remove the dependency on make in this [quickstart](https://www.spinkube.dev/docs/spin-operator/quickstart/) but want to check that isn't dupe work first.

**Comment by kate-goldenring** [comment]
I believe it is still unresolved. `make install` inside the `spin-operator` repo is still required in the quickstart: https://www.spinkube.dev/docs/spin-operator/quickstart/#deploy-the-spin-operator

@vdice mentioned we are moving the spin operator into it's own helm chart which should resolve this

**Comment by vdice** [comment]
@macolso this still needs updating as you've pointed out.  I think there were rumors of going kustomize?  There is of course the helm chart as well.  Anyways, will be great to get rid of the clone dependency and either option would be great!

**Comment by ThorstenHans** [comment]
This needs to be addressed for several parts of the documentation

- [ ] Quickstart -> :PR https://github.com/spinkube/documentation/pull/98
- [ ] Scaling with HPA
- [ ] Scaling with KEDA

**Comment by ThorstenHans** [comment]
I think we could close this one @kate-goldenring 

All references to `git clone https://github.com/spinkube/spin-operator.git` are related to inner-loop dev documentation and/or the contributing guide

**Comment by kate-goldenring** [comment]
closing as completed
